apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-project
  namespace: argocd
spec:
  description: Project for cluster-wide platform services
  sourceRepos:
  - '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: cert-manager
    server: https://kubernetes.default.svc
  - namespace: kubernetes-dashboard
    server: https://kubernetes.default.svc
  - namespace: infra
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
