# ==============================================================================
# ENVIRONMENT: Staging (Frontend)
# PURPOSE: Integration testing and preview
# UPDATE POLICY: Automated CI/CD image tag updates
# ==============================================================================

image:
  tag: "dev-c1c3e4a8"
ingress:
  enabled: true
  issuer: letsencrypt-prod
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: infra-infra-compress@kubernetescrd
  host: staging.luumac.io.vn
  secretName: portfolio-frontend-staging-tls
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  tz: "Asia/Ho_Chi_Minh"
  nodeEnv: "production"
  internalApiUrl: "http://portfolio-backend-staging:3001/api/v1"
