# Description: Helm values for the PostgreSQL staging database.
# Overrides default values with staging-specific storage and configuration settings.
# Last Updated: 2026-05-12

replicaCount: 1

persistence:
  size: 5Gi
  storageClassName: "local-path"


service:
  type: ClusterIP
  port: 5432

sealedSecret:
  enabled: true
  encryptedData:
    POSTGRES_USER: "AgDvfsErx/YpGJ9mgYtZns8ClxmWqJwQh3Gpwd+qq5TBv7xCSygpJrlRKMrV/Qdkv3ySjj/O5mEhyXfjC3wLbVOKte9/aGXMh8LGLkatmC6WAhl1vgM5in/PdAS718gD2uwUF6CoZFsoTRHfNrzmnzOLgx0Ne0kZDjRTTryn2shilJuO/uVEiVrgkb0IllONhJ9P2Xur1RbzOSXWzdWCya2JYy9JSkrkjhkFSV664IgdcY2/b56IJ0FDqmPX8kf2OABObHnYQ7g6ia4bDb13U8HUDkCDaO6NQwDph59wolSCIsroiqyG7WdKf3X94C6/HMj3DNrUBXIhANPpqi9aea4vevTfGUYDq1O6fyByS9WfgFSpBx4XTyiBSyLHAK8CLn27/uJ8P3cRqJ5e2uW1OpkhrWMaNYF6RGcNaj4EZ56icitrFLY8J4G52PIta/Vg9nt7h7cQ/TXUx33HFygjo/FN9qc8/VlhfchaRYHE+/VeR1gzspnT+mZycE8+H/o2M50uXHM/o8or5yHXqUEjBCVRc15h4TNT9aiqZpVLQKp8ugSFVSz1JwSBUWIGtgXN66uaOTYUcLjpVLMAJrjGH1xf1xNqdtVWJJhX9BzMDp5hN1FrzaC1/H3Hz/81nazQT4SXdBpkgDWnMUteQ7cRz2UMwlx6uLXj2hme0/saHsj0IDCx9Ng/m51X1j860uPfz97rYWz8WFkkmP9W808i8g=="
    POSTGRES_PASSWORD: "AgCt29CHeSQkexRJj3CjGTf2zMDkDPFza+OZR4lPr5koV9Y2I8S21y6zru/sCW7J6JKRqx7X45JMTDNdiCtY57ePKPMHm9leo7Le/YCWCpg5VQ2EpefXTeuDMX0q8tqfEe22QMafyeSvj9foo8oXuVq8l0MJV8ifKA3SNO9g4KEY43jYiAXuZkjnOSja/kA20H8x7SCFeD2ND74Pk92ABBZAxf2v2ZXvIx32MnaDlUubJtJxMGVe27AW8ak70oAL57AlgAWTg9rmyi6X8wpGEKM3pZAjLPhoBIyTM6dYWyX9umAzT0MMD6tM3W6V6iqNljHhmuXVUb/YumTH/oxNOT3b/twh+c9W1ToSgQTvUs4Z3sAxpz79pnagtpJlInZsHXto+CIrLlskqEIrQga5B+qP4Qs/VxP0wfI7SzXkHv4YhlErsQyzPMEcamXmqrh8xwmzkhq+5gbxhzJHpuGFne7dvc9esYOOuqJ4hyjX/iySaA+597H6brFUPZYIALRFye1INRtjPgNyUU2BPc4e6lB+H9coH5sui3J80s1+ZuzoKtwMhtsUI31jvcnJooWHYJzuFftAizJdd058LxAKOYNzuw2c/z4CX/NePuEmA9JsnOGD85NCut35SNlsEXsHfQYrl1LjCLyoNHGUFKo5i4FIngoaT01g31JYZO8B2osBCh9EtOkz+myJ27yoD3aGUBZw49LhyJrY0NNk"
    POSTGRES_DB: "AgB2uwhUueBmxl+9ZTmzZ6c7wirJw2+Omc8UCLW7IQelkxgUtsOaMtTJvWkB54+PgeBX3I4TwSrm88jhMQ5wvgHiCQXr2i/u+pWqnVe3T/e9gaaMxp4fdna9Pcctp3ujTJlvRmX/7zHZ3sWCWjFKfkSdwtKK3H5HT/iqzWOW0o5woIaY2uMFsjzhTV0hOFfV2DYoJp53pLU3P6Ks6nSzZO18Hgz/+5p1pBHm+ppJ4SnakK75BrTrM5SKK9nK1PHa0H2y7nCV3kTB/dk6b3DzaaCYAv6XMfnwwxdYnOyJbwlRP+Au6i0mwmytQ2wXDG+2T3GPfMvFPPLDWibl2r2+RApT5ni2LCMtLMc6kcXvGE2JvAdwPzpPzLzKF5W1Qq7yMFUy5W+6TaLkbMxuoTBwPMOJKgIRlkkOyq07Ue0aW6nzcTJkaVNGZX9L8U/rvpmTRmS5kix7ELEJl/hN+Y5/MAx+DdAGjauxb71wePc+E/v76/8dRX3LGYXgOsvV/Kgk1z/+OOhdE97igy3CqOpK6+JTG9BrxX3xxDNiEkO0+z2GZklj4ow10wdPUpWjduM2ZunTQJRgcdth+kRKMrQgk01+L3+srdXTBqRYVxbbIGtUUNC5vHjRQOTOS5WerRwFT2zwQIh36fcdmx69kTvmL79IB3iv3Zd3VctcArQNlyMJDNdVNiMSYNIzHk1BdHZwqREemWIl8wRuYTguoc9oVDpQDQ=="

