# Description: Helm values for the PostgreSQL staging database.
# Overrides default values with staging-specific storage and configuration settings.
# Last Updated: 2026-05-12

replicaCount: 1

persistence:
  size: 5Gi
  storageClassName: "longhorn"


service:
  type: ClusterIP
  port: 5432

sealedSecret:
  enabled: true
  encryptedData:
    POSTGRES_USER: "AgCL9P39jWwx8IOmHEFAPKAnihuSHbRgB8rPa53UN2Hvcr8CBeQAPuUM+lzsIp0S28AnE63RkCzmWKKY8Pl9DHMc9MSguo1RMp86WSvsBcYRRA3w8b0MAtfih8lDQLcLFGCqIwSZqx+QOKq2jcJiZfX11+uiPbBCsZGSL76+G7jJWutawPK/r6JN5v9tHPyIcjKKtObunnIAXihNmbOCsQ2VTLaW8JXU+7k3wSj8TlcfZhbyb0ryiSpR7/Uas1SqkpBXLgJCEYGRf1Mf+yS6op9lmQ20A9PbdTFr1sZeQLFkY+dQsZGeqOZJkGOlwoyk4i/xx6DIHLWu2pMzVr9No5L2ziJIbz6Enxq9H1eLolxltiXW0ZRXUVEzjrSASzx4lHM4xcdtVYfXt/B2yn/Bn/FmMvAWF/hX/qgzNkAQOhMj3vOL76ddq6VYDrpWyVJXbrnEv/rwGLurf67tZZCcrAtjVdp8SXmy50OIBA9bNUpfbO/3kTSKvIDXrHBCQeixxbor9+Zwv1EQwflajWLw4sOnIQvLcsXH7icJEe6ILr4fANTBjr6wldBsKbm+vYkym+v83ynpnHvD77vY04++vYMrdiWihdnf1Wr6BNBO8m+8ZPqnBGuy3g3Ny36KEVcR9UFTbHxc7mdBT41ohi3z4awoOjCwegdzmDXJQrQkt4Nq4vXB6f7WsnnNAcnoTskOLQABslSfnwU2MrhSiNWSPQ=="
    POSTGRES_PASSWORD: "AgBqk05fMIxbYtAPKUYr4l3ykvk0lj5h0OVS3TQINC9VZwRizgGzZwHOTisHGToWQyTkgeamIR4AAxAAP5RAywFVJUGY6kCZgBS92C/g+UDum5F0/ROK4yFWhOS4HsfRfFnmJWclX5N00PuyWobBLaP+QgbdFB+KcfGCgLoUXZamZ5+0LyMXQZVpEA7KZgh1mgzKnWuZNsOqAdrjVj2jv7qRcPZ1lvpjDbXd+nmYe2MuP1H7rXsM4mq4tQ/jkt/dHEcT3s6tMpaNdHaoB/OkY9roKoZiHtUAMEcbwC3+Fm+XJL3aD3ujjqIIbXVB5liNn7sHNBrGrvmlVbLYpczqYnDjTfO5Kum+OvGzY2EQmMdNSGbaDfrLPqY0jIUBHJZU9DgWHBZpQnWlwSFwFkT65ZyWcfQ4E3xaIkQ82o47SiV193elPrVSbv72WWWs56gvv4SmjKyygft0AS48Lr/Lsk6guZ0sdJ4QI2DDx5rqu1s9YKyKV7UBTbM/kRGZUSIeIRKkvHJf33ni/w3vEVRj4gsjHfhZ4tr7JI7vWz4LDEGlGYCaqt4A4dPFAYa1lQ7qnpm1qhJkXgrBoRvXVDJFOkH+g8+a/ooFlc1s+Buua3D+7bzPySmAWdGZEIp15SR370+6X6qwgnIFC4Otv05y2CSW1+jnibRiIqxPr06hSEShunnP0JPnbOpyjzy3IIXUVpy7D4wCNmT6dx2H"
    POSTGRES_DB: "AgDQ1xuYKoBOM6rUNCZHsMXbiuYs6nuwWH/U7MV4cRMkjyhhjPkkyuppebJghD94TfMLPjTe8fAC3Y1rFRDVi7Q9UEm2Z4wZJYYdFKDmbrgPnwwrJcdIDJ7C26ETNZo+ByA+S8yKZkFCWQHiejeo7T1ArXGaRREtoaUlyFmfiMwAdnId7DXLpNniZ6wAAdLFl75xUabc8YmujsmeigerGw4C3TYz4OWg0wU+1ztT2M4l2uT7Iw2ChRRfwtza8WP+3Po3JLswKTzIkZpbumKXqxNyLbx3EtH7JCM2vlv/crZZgEBN66lV1BMFp5qW0QOCnrsuYUHBbl0GfD2yODvB76rOX8knZkhgpVXFuR3Almor+34VNfzJaZRu3YuyfCYVpha0gg4z8mx6FS23rH4VcMSVtO2W+F0M3vdHxvbpFz9Q71tpC4Ocxw8hOocsrWiU7f8wBleFclFYLMP/hc1tKR//VzIrfHb4Xk8DvlpAzqqYHo9lYb8saCTud58nL3JDoqChvVSBet1PYDrbLT1ioDcc5RmcZPjwbjoAHhzcRyr7qLx/yi75z2v0xmRqFFHL88VWmDImSJbPUr/yfR4z+c0xOSXggSIDQg68avW0R6GMHjBVu0donN8mlVaf0mxIwGLOvUZ2BUtCxq4M4oBWl2OKLg1EFhwGYxwb3AqZ31YI55GyDsUpttJ8KshXFfJzriGqJzoDLdg0hXpgRidCbe8LyA=="

podSecurityContext:
  fsGroup: 70


