---
- name: Ensure base directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
    owner: "{{ ansible_operator_user }}"
    group: "{{ ansible_operator_user }}"
  loop:
    - /data/k8s
    - "{{ manifest_dest_base }}"

- name: Sync k8s manifests from ansible-node to remote
  delegate_to: localhost
  become: no
  command: >
    rsync -avz -e "ssh -i {{ ansible_ssh_key_path }} -o StrictHostKeyChecking=no" 
    {{ manifest_src_path }} 
    {{ ansible_operator_user }}@{{ ansible_host }}:{{ manifest_dest_base }}/
  changed_when: true
