# Description: Production group variables for Ansible.
# Environment: Production

env: production
is_production: true
ansible_become_password: "your_production_sudo_password"

# K8s Node Roles
k8s_role: master
node_labels:
  - env=production
  - role=master

# Infrastructure Services
traefik_enabled: true
cert_manager_enabled: true
argo_cd_enabled: true

# Traefik Configuration
traefik_additional_arguments: "{--accesslog=true,--accesslog.format=json,--serversTransport.insecureSkipVerify=true,--providers.kubernetescrd.allowcrossnamespace=true}"

# Project Configuration
project_name: portfolio
k8s_namespace: portfolio

# Kubernetes Dashboard Configuration
dashboard_namespace: kubernetes-dashboard
dashboard_admin_user: admin-user

# SSH Configuration
ansible_port: 2222
ansible_operator_user: macld
user_home: "/home/{{ ansible_operator_user }}"
ansible_ssh_key_path: "{{ user_home }}/.ssh/id_ed25519_ansible"
