# Variables for all environments
ansible_user: macld
project_name: portfolio
base_path: /data
domain_name: "luumac.io.vn"

# Databases
postgres_version: "16"
mariadb_version: "10.11"
db_user: macld
db_password: "your_secure_password" # Change this

# SSL & ACME Configuration (DNS-01 Cloudflare)
enable_ssl: false
acme_domain: "luumac.io.vn"
acme_email: "luumac2801@gmail.com"
cloudflare_token: "YOUR_CLOUDFLARE_API_TOKEN" # Update this on target machine
ssl_cert_path: "/etc/nginx/ssl/{{ acme_domain }}"
