{{- if .Values.redis.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    redis-password: {{ .Values.redis.encryptedPassword | quote }}
  template:
    metadata:
      name: redis-credentials
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
