{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secretName | default "portfolio-secrets" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- toYaml .Values.sealedSecret.encryptedData | nindent 4 }}
  template:
    metadata:
      name: {{ .Values.secretName | default "portfolio-secrets" }}
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "backend.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
