apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
        runAsNonRoot: true
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          runAsUser: 1001
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.service.port }}
        envFrom:
        - secretRef:
            name: portfolio-secrets
        env:
        - name: TZ
          value: {{ .Values.env.tz | quote }}
        - name: PORT
          value: {{ .Values.env.port | quote }}
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 15
          periodSeconds: 5
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/uploads
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: {{ include "backend.fullname" . }}-pvc
