apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- if .Values.ingress.issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer | quote }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.secretName | default (printf "%s-tls" (include "backend.fullname" .)) | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "backend.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: {{ include "backend.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
