stages:
  - deploy

variables:
  K8S_NAMESPACE: portfolio
  TZ: Asia/Ho_Chi_Minh

.k8s_auth: &k8s_auth
  before_script:
    - echo "$KUBE_CONFIG_BASE64" | base64 -d > kubeconfig
    - export KUBECONFIG=$PWD/kubeconfig

deploy_apps:
  stage: deploy
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  tags:
    - agent-1
  <<: *k8s_auth
  script:
    - apk add --no-cache curl jq
    - |
      # Tự động lấy Tag mới nhất của Backend
      BACKEND_TAG=$(curl -s "https://hub.docker.com/v2/repositories/luudinhmac/portfolio-backend/tags/?page_size=1" | jq -r '.results[0].name')
      # Tự động lấy Tag mới nhất của Frontend
      FRONTEND_TAG=$(curl -s "https://hub.docker.com/v2/repositories/luudinhmac/portfolio-frontend/tags/?page_size=1" | jq -r '.results[0].name')
      
      echo "Latest Backend Tag found: $BACKEND_TAG"
      echo "Latest Frontend Tag found: $FRONTEND_TAG"
      
      # Triển khai Backend
      helm upgrade --install portfolio-backend ./helm/backend \
        --namespace portfolio \
        --set image.tag=luudinhmac/portfolio-backend:$BACKEND_TAG \
        --kube-insecure-skip-tls-verify
      
      # Triển khai Frontend
      helm upgrade --install portfolio-frontend ./helm/frontend \
        --namespace portfolio \
        --set image.tag=luudinhmac/portfolio-frontend:$FRONTEND_TAG \
        --kube-insecure-skip-tls-verify
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_COMMIT_BRANCH == "main"
