stages:
  - deploy

variables:
  K8S_NAMESPACE: portfolio
  TZ: Asia/Ho_Chi_Minh

.k8s_auth: &k8s_auth
  before_script:
    - echo "$KUBE_CONFIG_BASE64" | base64 -d > kubeconfig
    - export KUBECONFIG=$PWD/kubeconfig

deploy_app:
  stage: deploy
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  tags:
    - agent-1
  <<: *k8s_auth
  script:
    - echo "Pipeline triggered by $CI_PIPELINE_SOURCE from project $CI_CONFIG_PATH"
    - echo "APP_TYPE is '$APP_TYPE'"
    - |
      if [ "$APP_TYPE" == "backend" ]; then
        CHART_PATH="./helm/backend"
        RELEASE_NAME="portfolio-backend"
      elif [ "$APP_TYPE" == "frontend" ]; then
        CHART_PATH="./helm/frontend"
        RELEASE_NAME="portfolio-frontend"
      else
        echo "ERROR: Unknown or missing APP_TYPE: '$APP_TYPE'"
        exit 1
      fi
      
      if [ -z "$IMAGE_TAG" ]; then
        echo "ERROR: IMAGE_TAG is missing"
        exit 1
      fi
      
      helm upgrade --install $RELEASE_NAME $CHART_PATH \
        --namespace $K8S_NAMESPACE \
        --set image.tag=$IMAGE_TAG \
        --kube-insecure-skip-tls-verify
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "trigger"
    - if: $APP_TYPE # Chạy nếu có biến APP_TYPE (phòng hờ)
