apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore-blog-staging-recovery-v2
  namespace: velero
spec:
  backupName: daily-backup-20260704190005
  includedNamespaces:
  - blog-staging
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  - csinodes.storage.k8s.io
  - volumeattachments.storage.k8s.io
  - backuprepositories.velero.io
