# Description: Staging group variables for Ansible.
# Environment: Staging

env: staging
is_production: false
ansible_become_password: "admin"

# K8s Node Roles
k8s_role: master
node_labels:
  - env=staging
  - role=master

# Security & Network
ssh_port: 22
fail2ban_enabled: false

# Infrastructure Services
traefik_enabled: true
cert_manager_enabled: true
argo_cd_enabled: true

# Traefik Configuration
# Using v2 compatible flags for staging if necessary
traefik_additional_arguments: "{--entrypoints.web.http.compress=true,--entrypoints.websecure.http.compress=true,--accesslog=true,--accesslog.format=json}"

# Project Configuration
project_name: portfolio
k8s_namespace: portfolio

# Kubernetes Dashboard Configuration
dashboard_namespace: kubernetes-dashboard
dashboard_admin_user: admin-user

# SSH Configuration
ansible_port: 2222
ansible_operator_user: macld
user_home: "/home/{{ ansible_operator_user }}"
ansible_ssh_key_path: "{{ user_home }}/.ssh/id_ed25519_ansible"
