apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-velero-configs
  namespace: argocd
spec:
  project: platform-project
  source:
    repoURL: https://gitlab.com/portfolio-macld/portfolio-infratructure.git
    targetRevision: main
    path: platform/velero
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
