apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.auth.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.auth.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.auth.database | b64enc | quote }}
