# Description: Ansible inventory file defining hosts and groups for different environments.
# Includes build-runners, staging k8s cluster, and production servers.
# Last Updated: 2026-05-12

[build]
build-runner ansible_host=192.168.157.109 ansible_user=macld ansible_ssh_private_key_file=~/.ssh/id_ed25519_ansible

[staging_k8s]
k8s-staging ansible_host=192.168.157.133 ansible_user=macld ansible_ssh_private_key_file=~/.ssh/id_ed25519_ansible ansible_port=2222

[k8s_server]
k8s-staging
k8s-digital-twin

[production]
# production_server ansible_host=YOUR_PROD_IP ansible_user=macld ansible_ssh_private_key_file=~/.ssh/id_ed25519_ansible

[control]
ansible_node ansible_host=localhost ansible_connection=local
