---
- name: Create frontend directory
  file:
    path: "{{ app_root }}/frontend"
    state: directory

- name: Synchronize frontend source code
  synchronize:
    src: "{{ playbook_dir }}/../../frontend/"
    dest: "{{ app_root }}/frontend/"
    recursive: yes
    delete: yes
    rsync_opts:
      - "--exclude=node_modules"
      - "--exclude=.next"
      - "--exclude=.env"
      - "--exclude=.git"

- name: Generate .env.staging for frontend
  template:
    src: .env.staging.j2
    dest: "{{ app_root }}/frontend/.env"
