---
- name: Install PostgreSQL and dependencies
  apt:
    name:
      - "postgresql-{{ postgres_version }}"
      - python3-psycopg2
      - acl
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is started and enabled
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create database user
  postgresql_user:
    name: "{{ db_user | default('macld') }}"
    password: "{{ db_password | default('macld@2026') }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
  become_user: postgres

- name: Create portfolio database
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user | default('macld') }}"
  become_user: postgres
