---
- name: Add Traefik Helm repo
  become_user: "{{ ansible_operator_user }}"
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "https://traefik.github.io/charts"

- name: Create Traefik namespace
  become_user: "{{ ansible_operator_user }}"
  kubernetes.core.k8s:
    name: traefik
    kind: Namespace
    state: present

- name: Deploy Traefik Ingress Controller
  become_user: "{{ ansible_operator_user }}"
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: traefik
    values:
      ports:
        web:
          nodePort: 32080
        websecure:
          nodePort: 32443
      service:
        type: NodePort

- name: Install Metrics Server
  become_user: "{{ ansible_operator_user }}"
  command: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

- name: Patch Metrics Server for self-signed certificates
  become_user: "{{ ansible_operator_user }}"
  command: >
    kubectl patch deployment metrics-server -n kube-system --type='json' 
    -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--kubelet-insecure-tls"}]'
