apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: portfolio
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: portfolio-strip-api-prefix@kubernetescrd
spec:
  rules:
  - host: staging.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: portfolio-backend
            port:
              number: 3001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-frontend
            port:
              number: 3000
