image:
  tag: "latest"

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: luumac.io.vn
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: portfolio-frontend-tls
      hosts:
        - luumac.io.vn
