# Description: Helm values for the PostgreSQL staging database in K3s.
# Overrides default values with staging-specific storage (Longhorn) and configuration settings.
# Last Updated: 2026-07-18

replicaCount: 1

persistence:
  size: 5Gi
  storageClassName: "longhorn"

service:
  type: ClusterIP
  port: 5432

sealedSecret:
  enabled: true
  encryptedData:
    POSTGRES_USER: "AgBKRIl2Cn2m1vE2fN38BNUzkNiy7oX/qCLs8fSATC4d2uetG5oBu/5lmfC+3PgiHxQtXVmBBHZ/ZLt87HPX15s8//qXGLJ6QJubXrHd9a036tq0rNqfpgYZqVenqhtqhhvV9uBCIQ8iLdzThr0nmtaRhj4+8LiWg77jJ2mtKGeMomngJ7hwSWMue3rJOw9u4nU/dcwzUjWZdxqhMujeIVl+WDOTO65vOlurRwSdGDk04cjvqIX7zHaLJ1azZZr60H4/s9TxKsY1oCN1mSodPUvoVGOyvTKvQdcZ5Bw26s3YYFSVN6tbcYmd6YdZMLa6mAe10O8XJIcYX2G9yPfOAsW32WbUGlkeRFsUpKPNG/GMq3XPb4aBLO72j57A+S8LnoHjiJ56QODPEQq9L9a4EdYGZma/TyZGyOBQeeZtVbUhffnA00Ph6CTTrz1Ov9b+DkTuXFidhP7njgcdnZCXJqHjDpas6R4g52879U3a4BN8khAFoeYCGBUjKycUMJsKRPks7tUTz8KbXYhjs+uZKjwX7uv4U/ZSqpkchvZdOQCJLyFDCPQ6RBoAxv7/19RYmN3dBdCJik6XCK6ThoevHW48TdMYo2T3w3l8ky58yCXmwGW6T3OOAfEeSJX8wZnN8aAWVf6NQMP1gfC0CxYQ1Er0cTcDIeYDHqUwLQyHtynMhxrbiMZE656YNNGSd7gWNx0P1cw35pNrkqE="
    POSTGRES_PASSWORD: "AgBv8M82kPIRnBul9esnCAV40HtN8Sz3fHg3/NmkT8D8m626VAzkZncRSTGIV3qCkNLKz5/1aAgD67Y5olvwU1CtUxpBIZvAu8GuYT7doaIpVPB5j7D0TIGt9tFBlsZQopgtTutoxLPMdaHMV4FvwrO1rIatxNzLZYc+oV6dKvSH5hOHaeL1U0kmGpdOSfPubfvaSbf+W+Zrmx7lW5XZOkhw0/hvO8KYPQ5PjS4QKm4Q3NQTsWbSfDqI3/Q2quPrA6Go0WJv66tzestcbjJY8gelMuIQi4A574oNw2MbulOpfBOdnUqkRsDPm6NCgIGVaGPf5WqhGK6U6CJG5FMvU5sLmLGmP18oXn66+jFPonOmgvckIyQY/Wmg8Ut6SXfQgGLHZplM6CAwpDlpwQQOgK1o8ZjiEKSqADPorSerWRfeciJp9IB0/9ZfEQpy+TU6Ret5XOZxov9w3lxHe/aLpRrDGuQqwvLjVP7i1Q8g6E8UKT359KW3qVqDD+3ZwnPf/ZL98ebDzq75aGid9TF75ch0k8rGaW4JdzXNE5RfCXzJK8QjUkMVY2oLotK8BwvkOMnORfWAwhVpSAefiSwWRqRe3qcT9nFiXupd7Ea7JDpBgZpa2XPy2BG9BGuU00JS0kEQqTmffHEqnwGOIu4066lYiiGSI8e4T7gkF/YaSVyxgss4e/VMSjNR5aX/L5cGFvkaku+lxGuKD8EJS/Z6m+aE"
    POSTGRES_DB: "AgAVmJDk792s79mouBwBHcvfX571IOpfgtouAxnwC3LQMpB1Z8qSnxTjEPoJlhmIxFaVl1s+P/xq0SWfTvlhcKaEc4LWLntCpZgtBjOk/PnGOtN2NJIgbH8sVqmQTKQL1/5prXkJT4fhA93ktSnc5/rKwtBNszQcAoPLLAex/eXNHX/FZMwW1AtX6GQ4JW8kdky5z9eCEM54QgP003BQyPoEbM8TBChpB3fD0qYxg5H3Lm0jScN+ipvphr43vK6uh8uSRVb8Vy2BzupFNjvX1xda8VySut0YaTl1ZZSrV6ZpsXrj0i+BENWTwqZZYk44Y5JQIqTaADoZCd2Rmf//DyKE9No5L5ElOfjmAebq7oNOPwflKb22I6L9nCRidTnbivSA/Zeo9OVzC8OQYdwxB4wBjck41vt1/h2rmEknN5RDrEHO4QS0zOFQVaRmUOvzuSTkhYo9K8JSQuBTt+E6+yOdj+KWAhhLeSvHxBOtKXtkqxb4h2CyzthA+0cRLBQElM3McOTVpQWL9hv+G5W5+zt/SWdbcZ5iBWpgnyY4jHEnUzEisAzZWNXJoAPLMS0LNHUGNL6Dh8czKsDRiULwC9RP3DpuOMTYNXcEKBq9i2+43RHXZ+O/Q75Na8kwmCArZj+y8cbP6LwqThH4UolmQT9yDiBRIr8SlmfC7kom1AUNDXP4XrMstBjspSczpLJRc1XGeynFD3H6bfA="

podSecurityContext:
  fsGroup: 70
