---
- name: Deploy Portfolio Application to Kubernetes
  hosts: k8s_server
  become: yes
  tasks:
    - name: Ensure project directory exists
      file:
        path: /data/Portfolio
        state: directory
        owner: macld
        group: macld

    - name: Sync source code to k8s node
      shell: rsync -avz -e "ssh -i /home/macld/.ssh/id_ed25519_ansible -o StrictHostKeyChecking=no" --exclude="node_modules" --exclude=".next" --exclude=".git" /data/Portfolio/ macld@192.168.157.110:/data/Portfolio/
      delegate_to: localhost
      become: no
  
  roles:
    - app/k8s-deploy
