---
- name: Deploy Portfolio Application to Kubernetes
  hosts: k8s_server
  become: yes
  tasks:
    - name: Ensure project directory exists
      file:
        path: /data/Portfolio
        state: directory
        owner: macld
        group: macld

    - name: Remove old code directory to ensure freshness
      file:
        path: /data/Portfolio
        state: absent

    - name: Clone fresh code from GitHub directly to k8s node
      git:
        repo: 'https://github.com/luudinhmac/myweb-profile-blog.git'
        dest: /data/Portfolio
        version: feature/clean-architecture-migration
        force: yes
      become: no
  
  roles:
    - app/k8s-deploy
