apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-exporter-pod-monitor
  namespace: blog-staging
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
