replicaCount: 1

image:
  repository: postgres
  tag: "16.13-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

persistence:
  size: 5Gi
  path: /data/k8s/postgres-infra

# Cấu hình Secret qua Helm values (hoặc dùng secret sẵn có)
auth:
  user: portfolio_user
  password: macld@2026
  database: portfolio_staging

namespace: database
