---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBkV36mr3FOm4h/5gX1kHpMXUhUtQ/rZpHZReqa2ZAacVjwQ0k0VexnCNUrWBwYvNlwyaUkjVJ+ismdoYHAW9R/pbQeVLXPis42lRUHgjXNoFvRqilKDoobkfO9kwXtwhm778vRxEithZqK7CqXn/yDtEq2iaFdc+s6z2K/FcvzeFCzBqO+o1NzBMv0x0ll6lMBjtjVKzv8s/STZZOWcytL05e6fmvEkOjrf+SBX03PUHM4SraaqL6+zZkFbxvZU3B4aV8d/OW8mTbXvpTa9k7Of2c+YTE5s//Ct9J4O9FfnTcNR1CbyQiRBHLgUCWsV7/OrI4bxwfNJyBfsVD8BbwxCCpPWqtH4aOTbPQdmGXOMsiWCDJqvvtevlhdr5DVNhzrRkr4yEh7zmuffwK0V9vODALGY8x7qcVqWt721jHIw4sTAei1SyK2PL0h800bXnVQRWWEnkcxtM439Ir7drCgRb1PZNGNTujtbQyN1MrbFxuV/RmZGXMtOXmdG7ZMhydhBHHA7QCeygy5BnVfDVrdGgmcXYOAVI5VLP/TdmzeCfyhpOyRkjJxhZv4Co9IHumm22x04juB8jOQ4UeCIhG4cvgtqrRJtC1hCoarSCxIAwGFw9xXlBGk48rI+DbjOPEKUFmA5SawYIBWEtl8FcGYof4+eKR/KmS9l5ZdBTyPjfyxvly9K25lOG5CSKvormHnTrxVzf+8psiBqgnd3grWhGP9LNzHZtXEQDs/1ohpBI95Fnnq+pEyptZLJmmQetjev76BdEF6IUyciQiWDmgipdurXk1tMi7KJ2QbaDTF5phI+7ZP0e9+dC1gd6x6IlQTbQ0nFWRkX7Vun6jCamRpXst5CgKxhJ5JeIXUrpjZqsvS7a4pP3zCXc8cKJJBwKAaxdV3Ioc7WxzoekU=
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
    type: Opaque
