---
- name: Ensure the Portfolio directory is a Git repository
  shell: |
    if [ ! -d .git ]; then
      git init
      git remote add origin git@gitlab.com:portfolio-macld/portfolio-infratructure.git
      git fetch origin
      git checkout -f main || git checkout -f master
    fi
  args:
    chdir: /home/macld/Portfolio

- name: Pull latest changes from GitLab
  git:
    repo: git@gitlab.com:portfolio-macld/portfolio-infratructure.git
    dest: /home/macld/Portfolio
    version: main
    key_file: /home/macld/.ssh/id_ed25519_gitlab
    accept_hostkey: yes
    force: yes
  register: git_pull_status

- name: Notify about code update
  debug:
    msg: "Code updated to version: {{ git_pull_status.after }}"
  when: git_pull_status.changed
