---
- name: Ensure Portfolio directory exists
  file:
    path: "{{ user_home }}/{{ project_name | capitalize }}"
    state: directory
    owner: "{{ ansible_operator_user }}"
    group: "{{ ansible_operator_user }}"

- name: Sync Infrastructure repository
  git:
    repo: "git@gitlab.com:portfolio-macld/portfolio-infratructure.git" # You can parameterize the URL too if needed
    dest: "{{ user_home }}/{{ project_name | capitalize }}"
    version: main
    accept_hostkey: yes
    key_file: "{{ user_home }}/.ssh/id_ed25519_gitlab"
  become_user: "{{ ansible_operator_user }}"
