apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-backup-sa
  namespace: infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-secret-reader
  namespace: velero
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["cloud-credentials"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-secret-reader-binding
  namespace: velero
subjects:
- kind: ServiceAccount
  name: etcd-backup-sa
  namespace: infra
roleRef:
  kind: Role
  name: velero-secret-reader
  apiGroup: rbac.authorization.k8s.io
