apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16.13-alpine
        env:
        - name: POSTGRES_USER
          value: "staging_user"
        - name: POSTGRES_PASSWORD
          value: "macld@2026"
        - name: POSTGRES_DB
          value: "portfolio_staging"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        hostPath:
          path: /data/k8s/postgres-data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: portfolio
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
