---
- name: Ensure backend storage directory exists
  file:
    path: /data/k8s/storage/backend-uploads
    state: directory
    mode: '0775'
  become: yes

- name: Template Kubernetes manifests
  template:
    src: "{{ item }}.j2"
    dest: "{{ user_home }}/{{ item }}"
  loop:
    - backend-secrets.yaml
    - backend-pv.yaml
    - backend-pvc.yaml
    - postgres.yaml
    - backend-deployment.yaml
    - frontend-deployment.yaml
    - services.yaml
    - ingress.yaml
    - middleware.yaml

- name: Apply Kubernetes manifests
  become_user: "{{ ansible_operator_user }}"
  command: kubectl apply -f "{{ user_home }}/{{ item }}"
  loop:
    - backend-secrets.yaml
    - backend-pv.yaml
    - backend-pvc.yaml
    - postgres.yaml
    - backend-deployment.yaml
    - frontend-deployment.yaml
    - services.yaml
    - ingress.yaml
    - middleware.yaml