---
- name: Create nginx directory
  file:
    path: "{{ app_root }}/nginx"
    state: directory

- name: Generate Nginx configuration
  template:
    src: nginx.conf.j2
    dest: "{{ app_root }}/nginx/nginx.conf"

- name: Generate Docker Compose file
  template:
    src: docker-compose.staging.yml.j2
    dest: "{{ app_root }}/docker-compose.yml"

- name: Run Docker Compose
  become: yes
  command: docker compose -f {{ app_root }}/docker-compose.yml up -d --build
  register: docker_compose_output

- name: Display Docker Compose output
  debug:
    var: docker_compose_output.stdout_lines
