---
- name: Check if certificate already exists
  stat:
    path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
  register: letsencrypt_cert

- name: Obtain SSL certificate with Certbot
  command: >
    certbot certonly --nginx 
    --non-interactive 
    --agree-tos 
    --email {{ cert_email }} 
    -d {{ domain_name }}
  when: not letsencrypt_cert.stat.exists
  notify: reload nginx
