# ==============================================================================
# ENVIRONMENT: Production (Backend)
# PURPOSE: Live traffic handling
# SECURITY: Strict TLS enforcement with Let's Encrypt certificates
# ==============================================================================

replicaCount: 0

image:
  tag: "v0.0.12@sha256:7b389ff04aa88dc9f4d5c618aa2551fb60e1c3580772b3ea574640a9ad0bd968"
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Triggers cert-manager to provision production certificates
  hosts:
    - host: api.luumac.io.vn # Production API endpoint
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: portfolio-backend-tls
      hosts:
        - api.luumac.io.vn

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

sealedSecret:
  enabled: true
  encryptedData:
    DATABASE_URL: "AQA3uq8WLPE/BTsGWf9XwR7u1YKH/4W/FK7hX8g0xP+dqjdP8hY5eo+U/twsFbA7vX4BN5ZQg8e7fehEnfX3hDrX4ZfnY1eKvLhdAsnxdI37v+TIaJfOVYYXQZRy26BOSz8pcDifvcWWpanxF2VERrmT5Ug54FeF/ARhSzj6zeqDRHi7XgCXMFT7ykI24bK0qOlKhozYCEeRGILQf+gvI8FQBsozUVbIXXrxbGp9EP8tXHvzyICk72EZnPgVbP47Bmht4JG4pUylo57dm/pQuMs4mZ0mR9zjcVMWgsmToCj//96/j7TcQTvijxudoAHrUbfASuH3g/EJGx9FbA9THxYWevs7tftTsOaF3rnBTAZzZtc66WOGKBY+BS0tdWbdD8XuULK/6OLy6HSynrP42flTYXjkuoN2kO6+d7A06ctEjAQR1/QgCLYgfXJOSJtOCL7D78TqtSQQHX42W7fDEYpCbIkRFZNrFZ1Ys/iHq0TDFvQ9y9nKXzjjBVCkfl2ZfBvOweK9oJExDNikRXX3XHfe1jnYJIgVEwk6rA4="
    JWT_SECRET: "AQAW50zSGoZaKqmEQm3ZJLb31xFMtlvQ2Gl5rVr09muvuDu0b2AzPabqV24PTBMLU22Ca1Cu6z8jNwdJSZkRhBWu9LVFsrk4zXQftMnxQ0hGHr7R4fz9tHdlpdWCdy5F+FFBmb3312a7tk7q2WCJPg2MMruzBSL+xP+cHkeU4LV/KD1T1+86RkdrZBqwMmkATUWWL5smrjMx1G5zre7u0OHdiNiJDT1OoyFgOqedOPTv2JbpdgDgNpbruc7E21sHhwWVMM5guvrgKkCEqATVv5tDq/BCZ0syGTMMhywQ09Qsqde3QBtKtQIY6CbUkONKY8ojom+HxMbxJAtjDdvoUXSM7VERSpgWFxkMYaNbE4dhqzdWxbU+Zrorb33GXfd2T6huCJ047VbovduwFg=="

