# Description: Helm values for the frontend production environment.
# Overrides default values with production-specific settings.
# Last Updated: 2026-05-12

image:
  tag: "v0.0.10@sha256:243a02793196cf407f136e56b5e9796c7fbe3dc3fdd56890a8ffea99374a7e02"

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: blog.luumac.io.vn
  secretName: portfolio-frontend-tls
  issuer: letsencrypt-prod

env:
  internalApiUrl: "http://portfolio-backend-production:3001/api/v1"
