# Description: Helm values for the frontend production environment.
# Overrides default values with production-specific settings.
# Last Updated: 2026-05-12

image:
  tag: "latest"

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: luumac.io.vn
  secretName: portfolio-frontend-tls
  issuer: letsencrypt-prod
