# Description: Helm values for the frontend production environment.
# Overrides default values with production-specific settings.
# Last Updated: 2026-05-12

image:
  tag: "v0.0.13@sha256:c5e1245a0e4b1e245c54e2e054d1f7579491d32fead97456cdd3f83ee3c8c0f2"
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: blog.luumac.io.vn
  secretName: portfolio-frontend-tls
  issuer: letsencrypt-prod
env:
  internalApiUrl: "http://portfolio-backend-production:3001/api/v1"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
