# Description: Helm values for PostgreSQL in the production environment.
# Configures resource limits, persistence, and service settings.
replicaCount: 1

persistence:
  size: 20Gi  # Larger for production
  storageClassName: "local-path"

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi


# Database connection settings (used by backend)
database:
  name: portfolio_production
  user: portfolio_admin
  host: postgres-production.database-production

sealedSecret:
  enabled: true
  encryptedData:
    POSTGRES_USER: "AgAHz2C5B+EOjahTX/CCp2xMNtOOYcUyBIWn3Xe9s1fI3cpuat4iSNOPGqHFEJc5kyZJsqp7tPC3B9JT2nViK5zJbGyFBcQEkwD64Njoj8io6k29EiYsokWWVk97WS1c0ieGFqrjCi2ZwGVegSm/i4uZEOc09Decycqqw90wWAh6aNz9IiTYvjkcg+A4m/lPEQbM4cUnB2giKGAMX7tTEd9QsgGptMpjjddKHXUwSpikUnUh/CirRnUGJDtXTwkXMDGRXhZuZ3uiPFz1fcSQcmC165p/ATnu7z2OfN2oSOzd1pDdIvmCXIqW2h8og2UbCKim2bXFrAZl9zZnWDf9h896LRZN1PjqFD4ENBBdGuYSC/BDVuz1d1YJa1mbjC8C5ui9I2dtf6slxY2QFdQhgbfDMXW0Jef9lkaMIbo5brlVX+bBMqZ02F3YHispASKTO3IOXEQ7w6sTw/UXcQ+CnK1KLCLis1PVHgllP/7jmmG4JyzJ3ktc2NHKPDdmm3GiPc0VIQK9CWnIL1AS45+hDAP6vnMgTQSLGsmXZoJwkxbu+7wE8r02z6HadQ4Frl0mBORWHIaRtMFWR9oFU6SzUd7OvQWdQ//PM6q6yd+DKClHzY+5Qa/NhAPuu4tkZYAhNcREwm3cHbBpSelYx22hMwiTXWnRVmvSSeMToCzJpizCl64VtZl2eVAHBWsREaosaPZHq9WUFFSchZJd1aDIbw=="
    POSTGRES_PASSWORD: "AgA86T2j5NZkOkvPnbcBveT+30KdIYKCmXGWTVVXMu9HHdZ0B8gfqn3CoAV4dcxoDdFnQt7NPc8aSvl5RaP0i/3d7c53QETfjzaRgQq68GLXPR0dspYeeEWYEUQebL68mUAo2+QzSNTIKz+j3zSJb1qlZmecHTvU+OJnr52MU0Tha+bL8lMWU16uPiL6JywIVCdxKA6PCIF77CpYJThP5UAwKUrV6SaZhvOA2aQ/H/zGEPI62Jh/SxZrcgECQGCalY0IzXwt+1rY3Q3p3e4OsqtpSpvLf/AGKVswkEaN5GmaHV2kV95YQFw979P6AGmUq8WYRc/gIh42oQ38TJKFfQ5XEVixApEOeL7BCvxrz5UgImt0DEHnGi8EEhGztEhombOvI+EDrus1OAtoxuVSxWgIjHKeA30Gp0prnvKfvupDpvW1dpO139KPfEMD1nYIOmc2hs1b49vJweHXnnlYDsGYXgVgjciiY5NWQ5Ggch/UrC9L1VA4eQrUiG0rTe6/lxo0oY5MJE0jF1EaXz3jRhlr1z74gHQOSTeWvkW3NOu4bPCgR1aeHRZbHFQfOKSbd50l6D8jTsxYmizIZNX0fLKkA2h6BkCJ4FZTrfO9JOPv0lSJcPN9Geu8JWz3vic7k3D3hirYEhP0f6KN1iOSHi36QCUsIcOB9KI/yBGd2jP34HlJ60QzBu6MFjLDPxTfTZitoWX/czEWGdMB"
    POSTGRES_DB: "AgDvSga2RpJLYmUTse+eIWHPiGFlyXzkwsE+ssvYzDbBmMtxOKzZ+sxOTru1B4rSd6MT8DBKdUPkMTvVpE6XsVLwyndscgZuidY7EUCKPbW13llKYGQN61tXjc4aMYa8QVR8upVcgwk2D8z1HBqs/6QcMoyQF0NhUq0LPQn2PL+UXkgj9d6TspwR361Bnj+Av74NXqzhSR7vL0rNBbhXvsmGmSFHIBX7lnm4R4OGJI6fe4fz3ga0FVPTtf56SwwTRupK5CKm9Veaw7Rkkg0+T7bsUwZLXAGWGFlGxb0TbknPlS+0mlMWu86qlYr9XZZ/KXiHUAlczmObwGi0UYC0s6AJJY7LCEuDqefsSedk+0UvKktmOJD1psXzuV4iFbWANdyCU4vUrm2EsTaer/Rrlli/jFlZEo4lPsFfoz/hN8luS9lXHRktwaMjDyVndRdlksuvt/6hqK16xz5ItZ+nd6S93hk+GinpXwe9gyMghEQXmjHSr/kG/yL/yl8bSEGsZaX5vFDMh1bLSC6MykMHMiZafPQvvDcQ10fPJdrOX7+iFC2nalN0ntDqKZFmg05tybqgz4kumgCOHCgzfX3+A5nt7RcAfQTHehl2rD6ewQOhiaSTh2kfy34fomj7M1ciufSeuTv1AZZDA3DsupYHnkZstfAs9gbysIEWhQk2OBtIxixVJeaR5iPGPF/RF8YejHmn5unEnQ73zVr8vptfUAmJwo8wUA=="

