# Description: Helm values for PostgreSQL in the production environment.
# Configures resource limits, persistence, and service settings.
replicaCount: 1

persistence:
  size: 20Gi  # Larger for production
  storageClassName: "longhorn"

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi


# Database connection settings (used by backend)
database:
  name: portfolio_production
  user: portfolio_admin
  host: postgres-production.database-production

sealedSecret:
  enabled: true
  encryptedData:
    POSTGRES_USER: "AgBPsX/WJOEadk433YiJSJlPR9ieyg9ueps46nyTuFRIjmo5KqxobFPPXqGu/2nVmDhtH4Pfp1R4CtM8a7pAlBfzkv0uDZ6dOij59sv3WTV3oPBGm4SqZWTz1884OBOLbTOTYHZnR6te28pKKU4LsJnFj9960umz487Zrv5vr9QIPgf792vSDKkduMbJfmT6XPhrZfT6lgeeEIymYaHM3i4mm8vg8AhYZ/SsXr4Pp1anv69ngyjqJ+3SkXY3pQVMwDZ94Sg+4RpmW0Dk+tLvhKW6ypizbmOgSUfI6PwDOQhdZNUQwx1MaE3FY3JPEtFmgRfH14+8sdTGgL0qqFQOiceP/pExtRvTdL0lyxyoh6PvkpxEtECW5utxYBAXFnv0SqtMtlboasfGrSSmJSyQDoohC8oh3BgVyPU3YyqtaxGAffEVNtq5Na4q/4Ow9aEM4xEpoD5fNzf3x/ydyMlsjxd5yPjW6uTA/CNSHaTcYmpXTCj13n6uEr8mJqgqonM1zyEs88fl3K07SnOtD1xpQVY5Z6QjVgSDNUnoa+xrW101UsY4yOJfmInpPpGvcv2XFtZkofDcAky5D45f9vdwCxNQYdR3vmE/R/2UILCmKx0e2TszOw4bxzToVykNvAyhkKxiM4l4bbiwxN1Sqzvm99bbCpff1EX20sKMzNuhxPeeDjRP4KAZQ60rh0/Zr2i6x1Bl4CBqAaeQ7R5mvuYrfg=="
    POSTGRES_PASSWORD: "AgCPWUgHXIIMotrJEQ21UzHU9rZxhn947QkY4HunMCkdq/m8MRLeKQTnyqmVtxaoVYhNUdGuDtLd5oZxInSRZSsCRnXtYq5y6w0yWIk+KVY17/2F1YYju4x8lhuHnx//1HuvL2ziX63k994g2UgDd+ENn6D7fX9iDFARE4qUkC4i65MGu1zZsDrua3UNdjCw6cTp7B3QKoNlHHngETl6qyOJpkJr44wqrIfYmp0GeyP7C3m7h2hdysCE4aKVEXTS+9zNWiCyO+hL7jKrupwIL2+hp5Iu640ogXrXeuOP6p/BF7HOZYn2pNSspqMV631sntum5XH9MYT189Fh45OzmrI00A3wclCUCFb28pZ036N2Aa1EgtB8WM9wE6yDeENmR99EYUy/dcl4TS9X5WVQyReZMnP3q2d7o/2f7FyGR0yYDoHii9JEk4G/eLUcmzdnhXcVcv9BEHGKN849Fpupq/9CWJCkRqvNK5sTDKOjsZ4WlzGL0Q0CTj5ja2Rdte/xttiaqe4sY9v1ganQ7/7/AJ1ilYESA/Z3PYiIJSReFrhRjAx671J2Tap1sCgfPmabvQwj7f0o3qcji2JppYl370DEU8p+MBdLNCc70BjlbApVmBdYnw1QoskgUvoImLex5qwLydJSQHeN1PQECn2UBMHRbRgu9lOCPRWv2WnknjSH3Z5sA5Y1oERJu1DdX+Y2LO7nLmSxJ+wf/nkp"
    POSTGRES_DB: "AgDfz+0O0Zn9QC0lobMmJT7KV8Ud0aOjvekNE5eeyXNGS84hfaRZbhNJY7zMw3Yw+CXYW0PG4lPWe2lp7Ij20CW5P96qukF0u0jpOvuO5KCMQpbYRkoqztRhtyIH+YlYBbq6mBNSof+VUycvJxIFkd14KT6pgSPdKw2Gts14pM8k+w1mI9TI+UeXVcB3odVPIutEtJm8gsIKjZmDlnE4RWsCGMst8YPrkv7Z580Soda+0xB75+nEJCmFneLpuc8qQcGstnHW3g+R+Sg8tCjsvDB+hg48QaxMoguATcTINOD4PJRmikR+MaNlGhYOXUFjgMsxsoSPI5n3rZ+D/xVCJb2Ma8XYOkUE73UnnV1ObfLeL5aNSbdhPCb9qJ8YIDMz1XftFH2JliaUhlZvhB1Vzn8L8ojTaOKo6GVbU94pUy5lWCHqC47PSdto1gCrzVKJR+8F3MdWgUwD6FCBTtplXQXOyjSdaH+KsUu+tnBNbJLP/NbU+JnJBZzvez5Dk8xxypDlK3zO+evLo9bkSBhEzcxVwOpWzPlkKYSM/G8JRbj93BQmXS/Z9WyLamy8CIIt0GBVpKeQeGOL8AX7F7cBpENgNK4Z6gDghhRE4NWPQnhNQBoO0Xi/sh72ijgBGQ67LMs4Pxqeov2pdo9UcfzZWrMQ7IeXbRKjqsOzxqR66bgMMzeEtsdzkdx1OMw2KITBNY77b7gWXHyBC/GYVIu2G0jRnnuvnw=="

