apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-portfolio-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  encryptedData:
    url: AQCWNcunqgyr6jmfPFgY5Dgz6dj6QLT5oTC63nzsavoyv0l6gpiamXsIA/48i0PczcmyCftUwIa6KDp5fiJEYohk0F0UFRscn62RpYI0IxOORj8JtN6OWro0Rb6IF+BorAUZ+dM9BnlWOLb3vqJEOKr8YBQI9s+YyMVdZQeZ6eXaNbBJODDDrmbwaVjBsnkHMGfbt7TjIuRUr6Fz/JSPHe9ZM8NZect6TKEXTTYm57BfXHzZhr+hmodctdwps0/ELWVI0UFmPHskVVx9NmTYny6EuvlKSP/Eth6MDYKE3Bah7GxaLKhB48UJogA28264vWR8QtISH0ysG3+b5mkxvenNf+uTmUz1cXpWKcjpYMz0G9UUfAmH+t7nSCyFKB3kbDhMGpr5IN0kwk+PRgCobCdgHbnZwL+ZaHZoLwTPMcjkHP6czILsbkkTrCq9WxvI
    username: AQAK9vruS3rRKU0Lrg/U3LNdhfay/vGGKcMjPpUOyybdZ+0ktpcVBMMc65fC0Prn9ApUJFGjrsNcQfx8vr+YHxZA1WGGwSVvD8YckCWObcGLzIueyMJ2WfnzJyETUG4Jw6BGgo/K3tbl9ghG+yEshgeJX/+Ov1c8YM4Ap9S9RJ3F2F1tX9Zdxv3SYypNP+9gG3txZdJdqW0iJNk4KeyDqT+AAdXpnk3N7qLWlOIZFydR7iNTSCOrLofTntRpVDYCA2TgJZJ9V230ye9tANntydTDnMd4Sq7HiAeqQBHEM4UWPeHo675cqMbQrFcEWnl8+Ib8C4wv5tnSiIGVppt/+SDl2ZgYAkwulmcIu2cMeHt5+kSRD9ERvTAFJaWWv7bKsd9Wbn1xbfIPRQ==
    password: AQBSlH0RJPy352bEzfyevyJHtg6NQH7L3w2a2MAgVB/ueZff83lh+exCxmbNI++ELSv+PI4mZGg/0em+RhsrFPc8Zth7rkh93txMNTFaAaDv1uTC3TRPvZnPu0XOrCk5W6IeEaLqDdlZHDIC1e7tEaLI5029ArjMLYsCw9ldxuiDFAzDj6i0r5UnBmzDSF8FF6N1cIE1VVW1bl2WwZcy1VQ/PvVdF82EPJHIpr4nXAa4JQNEawUeZ3ihs7orimJ4AQm3ybV37HfHQxB+tKrwM581eMAmYKRTPPvSrT3dE+55ASUjQLlDy2Au6WZjZS7cPHQBHJG1KbKzNLnKJ/Uheg2ci2S1Mliw3nfMyxS0LgIioFB7ToD9MRT61MAhLaMTXMQosgw43r4vkyfbAfHUrw==
  template:
    metadata:
      name: gitlab-portfolio-repo
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
    type: Opaque
