---
- name: Sync latest code from GitLab
  hosts: localhost
  connection: local
  become: no
  roles:
    - { role: git-sync, tags: ["sync"] }

- name: Pre-deployment Environment Check
  hosts: build, staging_k8s, production
  become: yes
  roles:
    - { role: pre-check, tags: ["check"] }
