---
- name: Clean Kubernetes Resources
  hosts: staging_k8s
  become: yes
  tasks:
    - name: Remove all deployments in project namespace
      become_user: "{{ ansible_operator_user }}"
      command: "kubectl delete deployments --all -n {{ k8s_namespace }}"
      ignore_errors: yes

    - name: Remove all services in project namespace
      become_user: "{{ ansible_operator_user }}"
      command: "kubectl delete services --all -n {{ k8s_namespace }}"
      ignore_errors: yes

    - name: Remove all ingresses in project namespace
      become_user: "{{ ansible_operator_user }}"
      command: "kubectl delete ingress --all -n {{ k8s_namespace }}"
      ignore_errors: yes
