[staging]
staging_server ansible_host={{ lookup('env', 'STAGING_IP') | default('192.168.157.109', true) }} ansible_user={{ lookup('env', 'STAGING_USER') | default('macld', true) }} ansible_ssh_private_key_file={{ lookup('env', 'STAGING_SSH_KEY_PATH') | default('~/.ssh/id_rsa', true) }}

[production]
production_server ansible_host={{ lookup('env', 'PROD_IP') }} ansible_user={{ lookup('env', 'PROD_USER') | default('root', true) }} ansible_ssh_private_key_file={{ lookup('env', 'PROD_SSH_KEY_PATH') }}

[control]
ansible_node ansible_host=localhost ansible_connection=local
