---
- name: Sync latest code from GitLab
  hosts: localhost
  connection: local
  become: no
  roles:
    - { role: git-sync, tags: ["sync"] }

- name: Infrastructure Setup (Build, Staging, Production)
  hosts: build, staging_k8s, production
  become: yes
  roles:
    - { role: common, tags: ["common"] }
    - { role: manifest-sync, tags: ["sync"] }
    - { role: docker, tags: ["docker"] }

- name: Kubernetes Cluster Setup
  hosts: staging_k8s, production
  become: yes
  roles:
    - { role: k8s-cluster, tags: ["k8s"] }
    - { role: infra-services, tags: ["infra-services"] }

- name: GitLab Runner Setup
  hosts: build, production
  become: yes
  vars_files:
    - vars/secrets.yml
  roles:
    - { role: gitlab-runner, tags: ["runner"] }

- name: Application Deployment (Staging)
  hosts: staging_k8s
  become: yes
  vars_files:
    - vars/secrets.yml
  roles:
    - { role: k8s-deploy, tags: ["deploy"] }
