---
- name: Test Become Capability
  hosts: all
  become: yes
  tasks:
    - name: Check whoami
      command: whoami
      register: whoami_output

    - name: Print whoami
      debug:
        msg: "User on {{ inventory_hostname }} is {{ whoami_output.stdout }}"
