apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres/kustomization.yaml
  - backend/kustomization.yaml
  - frontend/kustomization.yaml
  - ingress/kustomization.yaml
