variables:
  TZ: Asia/Ho_Chi_Minh

  # =====================================================
  # REGISTRY
  # =====================================================
  CI_REGISTRY: docker.io
  IMAGE_NAME: $CI_REGISTRY_USER/portfolio-frontend

  # =====================================================
  # BUILD
  # =====================================================
  BUILDKITD_FLAGS: --oci-worker-no-process-sandbox

  # =====================================================
  # CACHE & DEPENDENCIES
  # =====================================================
  PNPM_CACHE_DIR: .pnpm-store
  TRIVY_CACHE_DIR: .trivycache

  # =====================================================
  # IMAGE REFERENCES
  # =====================================================
  BUILD_IMAGE: $IMAGE_NAME:build-$CI_COMMIT_SHA
