{{- if and (eq .Values.secretsProvider "doppler") .Values.doppler.encryptedToken }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.doppler.tokenSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    serviceToken: {{ .Values.doppler.encryptedToken | quote }}
  template:
    metadata:
      name: {{ .Values.doppler.tokenSecretName }}
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "backend.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
