- name: Generate SealedSecret for Velero
  hosts: localhost
  connection: local
  vars_files:
    - "../vars/secrets.yml"
  tasks:
    - name: Run kubeseal to encrypt R2 credentials
      shell: |
        cat <<EOF | kubeseal --cert /tmp/sealed-cert.pem --format=yaml > ../../platform/velero/sealed-secret.yaml
        apiVersion: v1
        kind: Secret
        metadata:
          name: cloud-credentials
          namespace: velero
        type: Opaque
        stringData:
          cloud: |
            [default]
            aws_access_key_id = "{{ r2_access_key_id }}"
            aws_secret_access_key = "{{ r2_secret_access_key }}"
        EOF
      no_log: true
