---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram-secrets
  namespace: monitoring
spec:
  encryptedData:
    telegram_bot_token: AgC4Mc7XO5ROImAP3Kcjs0LqQ830gLz1N4MnrWL0OXAZXClYe9qJfaBAoeVzGrb5H+ZFVTQ3ZDqHH50h16wtt+XFE2fGK+rk/cgFJkVEMtYX+Tk1DRQyaF9TPOvYF77j3Hvw6sVUv6433IUwIrCWQWpeAxekSsdUTVwYn7grwMX3icE0TgwtrhHIZDF3a5tWjk0ngR92+VyYEiZP5zkNj3kd/0fMmW0K4ZKfdZkAt306QiBBPjhm1D8WlM7hAsp52OpNq1aHVxHCLnXxpwBx4JTKI5Bd7RUnz/Iut/g5rWowykoCw20mGxekev9a9Z6ngDVPOH7GyyUst6NVSIwKHe+wSRZXFhHETpSxG8MkLKbqvSyDJky7ECwML1pScxOpWg1FMPMnwB8pxXtPZEsPHDLM6OP04La0tKqiRf4a/MlPF74scX+rBwaIkVRkC3gKsgK8kKj4sPDCsgbME4FGzJyuCxXXwshx6Rfl2wkXiZPF5YOhb2U7A2ROzHjdKTt6WZLivPt1EN0O67ZSTsC2kZgqj5I+c8kY6lT0TmLu1X5BIMglJOOksVVnkPjDsyO+F00D6jhpLGj5gVh2I36v3+6uSQd1DOuzva1TLrq307gGGA+PwlxxLnyIJgUNXcDmlY7qsjL02t/29boowxrhenBjLMntABscL8zcmf9ON/CfGY8MLt9WFjMs7/GBOW9l7SEWL1kxP0YjitrEtvbuJY9fbx2a4FP8ebJ6JHCWSJTN6joX4+YUa5melu9XMcEH
    telegram_chat_id: AgDsm368LtR3HIwfud4JfVkAkwyGXwHj1r1il12a/ozpzCTEyao3prNh7O5ck88wGrTG9zdnoxxR7RNVc7StBjFbkX6ivg0ekOVAHd5pK2ka6JR5niEiA4DeCMmtBgPHH+Nf6LrgbUQtwWS9eJ574Tz9HX29V3NSDW15V3XyGgE3QpqGAzHH5qSIum1/zq8ALu8JxbjxHPvmcJ066U8pX6EcZZjosIqNuP2g/LANoQpvzkPqibW16dcoAAA13GKiG91eVAU3YDUNmQUcdKa7iotrNE3JntUP8+yelNPVfykxwvuH5gFSSbtjelbSVYItqFWci0pF43AfsxMYQDa1va4i01CF4a14ovlnCcEz7wKkymsHRNQy6hjepDcLDUpRrq9Z4Dspg6zZeaQb+WJmmaHFXUm3BBMwhnQ8M3w9pd7i+KC7NVCtuqJFDHsyHOozKkyAqsVZKhQp9SLWTJlGrHSLdAecJFJRDRdeGjdUdZWrZIE/eaqjpvoTUuR9mThfiRY8al2GJ1iuE0y2QFvvxr9RWtqnHS4GxijQ8fFZZkqBZNn5i1WRrEWbrLYP1jfqETyTQdEGYa7eQP1DQTnX6PKv1Lcp1RwlHt7zxpDbM2nPZS7ul7mZYK7vNM68mW/cBBOagEmGFrwdtxYPL1Z1PHqhqYgDir/0psPH1Gksa0NzcLlzACQxphyy6D8Wv8YE/MEdaY9lw/R2TlVHiA==
  template:
    metadata:
      name: alertmanager-telegram-secrets
      namespace: monitoring
    type: Opaque
