replicaCount: 1

image:
  repository: luudinhmac/portfolio-frontend
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

env:
  tz: "Asia/Ho_Chi_Minh"
  nodeEnv: "production"
  internalApiUrl: "http://portfolio-backend:3001"

ingress:
  host: "staging.luumac.io.vn"
  secretName: "luumac-tls-staging"

namespace: portfolio
